from __future__ import annotations

import json
import os
import sqlite3
import base64
import hashlib
import hmac
import secrets
import threading
from dataclasses import asdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Iterable, NamedTuple

from .models import Entity, EntityBinding, EntityKind, EntityRecord, Event, EventStatus, F1Session, Follow, FollowLevel, NotificationRule, PushSubscription, Sport, UserAccount, UserPreferences
from .seed import DEFAULT_PREFERENCES, ENTITIES

try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - SQLite remains the local default.
    psycopg = None
    dict_row = None


DB_PATH = Path(__file__).resolve().parents[1] / ".data" / "matchnest.sqlite"
PASSWORD_ITERATIONS = 210_000
SESSION_DAYS = 30
VERIFICATION_HOURS = 24
DATABASE_URL_ENV = "DATABASE_URL"
DATABASE_PROVIDER = os.getenv(DATABASE_URL_ENV, "").strip()
POSTGRES_INIT_LOCK_KEY = 730219901
_INIT_LOCK = threading.Lock()
_INITIALIZED_DATABASES: set[str] = set()
INTEGRITY_ERRORS = (sqlite3.IntegrityError,)
if psycopg is not None:
    INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.errors.UniqueViolation)


class ProviderFetchState(NamedTuple):
    fetched_at: datetime
    status: str
    error: str | None


class PostgresCursor:
    """Small cursor adapter that keeps the storage layer compatible with sqlite3."""

    def __init__(self, cursor: Any, lastrowid: int | None = None) -> None:
        self.cursor = cursor
        self.lastrowid = lastrowid

    def fetchone(self) -> dict[str, Any] | None:
        return self.cursor.fetchone()

    def fetchall(self) -> list[dict[str, Any]]:
        return list(self.cursor.fetchall())


class PostgresConnection:
    """Translate the limited SQLite SQL used by MatchNest to Postgres."""

    def __init__(self, database_url: str) -> None:
        if psycopg is None or dict_row is None:
            raise RuntimeError("DATABASE_URL is set, but psycopg is not installed.")
        self.connection = psycopg.connect(database_url, row_factory=dict_row)

    def execute(self, sql: str, params: Iterable[Any] = ()) -> PostgresCursor:
        translated, wants_lastrowid = translate_sql_for_postgres(sql)
        cursor = self.connection.execute(translated, tuple(params))
        lastrowid = None
        if wants_lastrowid:
            row = cursor.fetchone()
            lastrowid = int(row["id"]) if row else None
        return PostgresCursor(cursor, lastrowid)

    def commit(self) -> None:
        self.connection.commit()

    def close(self) -> None:
        self.connection.close()


def connect() -> sqlite3.Connection | PostgresConnection:
    database_url = os.getenv(DATABASE_URL_ENV, "").strip()
    if database_url:
        connection = PostgresConnection(database_url)
        ensure_db_initialized(connection, f"postgres:{database_url}", use_postgres_lock=True)
        return connection
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    ensure_db_initialized(connection, f"sqlite:{DB_PATH.resolve()}", use_postgres_lock=False)
    return connection


def ensure_db_initialized(
    connection: sqlite3.Connection | PostgresConnection,
    database_key: str,
    use_postgres_lock: bool,
) -> None:
    if database_key in _INITIALIZED_DATABASES:
        return
    with _INIT_LOCK:
        if database_key in _INITIALIZED_DATABASES:
            return
        if use_postgres_lock:
            connection.execute("SELECT pg_advisory_lock(?)", (POSTGRES_INIT_LOCK_KEY,))
        try:
            init_db(connection)
            _INITIALIZED_DATABASES.add(database_key)
        finally:
            if use_postgres_lock:
                connection.execute("SELECT pg_advisory_unlock(?)", (POSTGRES_INIT_LOCK_KEY,))
                connection.commit()


def translate_sql_for_postgres(sql: str) -> tuple[str, bool]:
    translated = sql.strip()
    insert_or_ignore = "INSERT OR IGNORE INTO" in translated
    translated = translated.replace(
        "id INTEGER PRIMARY KEY AUTOINCREMENT",
        "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    translated = translated.replace("INSERT OR IGNORE INTO", "INSERT INTO")
    translated = translated.replace("?", "%s")

    wants_lastrowid = translated.upper().startswith("INSERT INTO USERS ") and "RETURNING" not in translated.upper()
    if wants_lastrowid:
        translated += " RETURNING id"
    elif insert_or_ignore and "ON CONFLICT" not in translated.upper():
        translated += " ON CONFLICT DO NOTHING"
    return translated, wants_lastrowid


def init_db(connection: sqlite3.Connection | PostgresConnection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS events (
            id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            sport TEXT NOT NULL,
            starts_at TEXT,
            status TEXT NOT NULL,
            entity_ids TEXT NOT NULL,
            source TEXT NOT NULL,
            competition TEXT,
            session_type TEXT,
            result_summary TEXT,
            importance INTEGER NOT NULL,
            raw_json TEXT NOT NULL,
            first_seen_at TEXT NOT NULL,
            last_seen_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    connection.execute("CREATE INDEX IF NOT EXISTS idx_events_starts_at ON events(starts_at)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_events_sport ON events(sport)")
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS provider_fetches (
            provider_name TEXT NOT NULL,
            cache_key TEXT NOT NULL,
            fetched_at TEXT NOT NULL,
            status TEXT NOT NULL,
            error TEXT,
            PRIMARY KEY (provider_name, cache_key)
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            email_verified_at TEXT,
            verification_token_hash TEXT,
            verification_expires_at TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    connection.execute("CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)")
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS user_sessions (
            token_hash TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS oauth_accounts (
            provider TEXT NOT NULL,
            subject TEXT NOT NULL,
            user_id INTEGER NOT NULL,
            email TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (provider, subject),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS oauth_states (
            state_hash TEXT PRIMARY KEY,
            provider TEXT NOT NULL,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL
        )
        """
    )
    connection.execute("CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions(user_id)")
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS user_follows (
            user_id INTEGER NOT NULL,
            entity_id TEXT NOT NULL,
            level TEXT NOT NULL,
            notifications_enabled INTEGER NOT NULL,
            hide_spoilers INTEGER NOT NULL,
            updated_at TEXT NOT NULL,
            PRIMARY KEY (user_id, entity_id),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS user_settings (
            user_id INTEGER PRIMARY KEY,
            f1_sessions TEXT NOT NULL,
            default_hide_spoilers INTEGER NOT NULL,
            timezone TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS user_ui_state (
            user_id INTEGER PRIMARY KEY,
            state_json TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS push_subscriptions (
            id TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            endpoint TEXT NOT NULL UNIQUE,
            p256dh TEXT NOT NULL,
            auth TEXT NOT NULL,
            user_agent TEXT,
            enabled INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute("CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user_id ON push_subscriptions(user_id)")
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS notification_rules (
            id TEXT PRIMARY KEY,
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            enabled INTEGER NOT NULL,
            target_type TEXT NOT NULL,
            target_id TEXT NOT NULL,
            minutes_before INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute("CREATE INDEX IF NOT EXISTS idx_notification_rules_user_id ON notification_rules(user_id)")
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS sent_notifications (
            user_id INTEGER NOT NULL,
            event_id TEXT NOT NULL,
            rule_id TEXT NOT NULL,
            scheduled_for TEXT NOT NULL,
            sent_at TEXT NOT NULL,
            PRIMARY KEY (user_id, event_id, rule_id, scheduled_for),
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS entities (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            sport TEXT NOT NULL,
            kind TEXT NOT NULL,
            color TEXT NOT NULL,
            is_seed INTEGER NOT NULL,
            created_by_user_id INTEGER,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL
        )
        """
    )
    connection.execute("CREATE INDEX IF NOT EXISTS idx_entities_sport ON entities(sport)")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_entities_kind ON entities(kind)")
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS entity_aliases (
            entity_id TEXT NOT NULL,
            alias TEXT NOT NULL,
            PRIMARY KEY (entity_id, alias),
            FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS entity_provider_bindings (
            entity_id TEXT NOT NULL,
            provider TEXT NOT NULL,
            binding_type TEXT NOT NULL,
            binding_value TEXT NOT NULL,
            metadata_json TEXT NOT NULL DEFAULT '{}',
            PRIMARY KEY (entity_id, provider, binding_type, binding_value),
            FOREIGN KEY (entity_id) REFERENCES entities(id) ON DELETE CASCADE
        )
        """
    )
    sync_seed_entities(connection)
    connection.commit()


def create_user(email: str, password: str) -> tuple[UserAccount, str]:
    normalized = normalize_email(email)
    now = utc_now()
    raw_token = secrets.token_urlsafe(32)
    connection = connect()
    try:
        cursor = connection.execute(
            """
            INSERT INTO users (
                email, password_hash, verification_token_hash,
                verification_expires_at, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                normalized,
                hash_password(password),
                hash_token(raw_token),
                (now + timedelta(hours=VERIFICATION_HOURS)).isoformat(),
                now.isoformat(),
                now.isoformat(),
            ),
        )
        user_id = int(cursor.lastrowid)
        initialize_user_preferences(connection, user_id)
        connection.commit()
        user = get_user_by_id_with_connection(connection, user_id)
        if user is None:
            raise RuntimeError("Created user could not be loaded.")
        return user, raw_token
    except INTEGRITY_ERRORS as exc:
        raise ValueError("Email is already registered.") from exc
    finally:
        connection.close()


def verify_email(raw_token: str) -> UserAccount | None:
    token_hash = hash_token(raw_token)
    now = utc_now()
    connection = connect()
    try:
        row = connection.execute(
            """
            SELECT * FROM users
            WHERE verification_token_hash = ?
              AND verification_expires_at IS NOT NULL
              AND verification_expires_at >= ?
            """,
            (token_hash, now.isoformat()),
        ).fetchone()
        if not row:
            return None
        connection.execute(
            """
            UPDATE users
            SET email_verified_at = ?, verification_token_hash = NULL,
                verification_expires_at = NULL, updated_at = ?
            WHERE id = ?
            """,
            (now.isoformat(), now.isoformat(), row["id"]),
        )
        connection.commit()
        return get_user_by_id_with_connection(connection, int(row["id"]))
    finally:
        connection.close()


def authenticate_user(email: str, password: str) -> UserAccount | None:
    connection = connect()
    try:
        row = connection.execute("SELECT * FROM users WHERE email = ?", (normalize_email(email),)).fetchone()
    finally:
        connection.close()
    if not row or not verify_password(password, row["password_hash"]):
        return None
    return user_from_row(row)


def create_session(user_id: int) -> str:
    raw_token = secrets.token_urlsafe(32)
    now = utc_now()
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO user_sessions (token_hash, user_id, created_at, expires_at)
            VALUES (?, ?, ?, ?)
            """,
            (
                hash_token(raw_token),
                user_id,
                now.isoformat(),
                (now + timedelta(days=SESSION_DAYS)).isoformat(),
            ),
        )
        connection.commit()
    finally:
        connection.close()
    return raw_token


def get_or_create_oauth_user(provider: str, subject: str, email: str) -> UserAccount:
    normalized = normalize_email(email)
    now = utc_now()
    connection = connect()
    try:
        row = connection.execute(
            """
            SELECT users.* FROM oauth_accounts
            JOIN users ON users.id = oauth_accounts.user_id
            WHERE oauth_accounts.provider = ? AND oauth_accounts.subject = ?
            """,
            (provider, subject),
        ).fetchone()
        if row:
            return user_from_row(row)

        user_row = connection.execute("SELECT * FROM users WHERE email = ?", (normalized,)).fetchone()
        if user_row:
            user_id = int(user_row["id"])
        else:
            cursor = connection.execute(
                """
                INSERT INTO users (email, password_hash, email_verified_at, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?)
                """,
                (normalized, "oauth", now.isoformat(), now.isoformat(), now.isoformat()),
            )
            user_id = int(cursor.lastrowid)
            initialize_user_preferences(connection, user_id)

        connection.execute(
            """
            INSERT INTO oauth_accounts (provider, subject, user_id, email, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (provider, subject, user_id, normalized, now.isoformat(), now.isoformat()),
        )
        connection.commit()
        user = get_user_by_id_with_connection(connection, user_id)
        if user is None:
            raise RuntimeError("OAuth user could not be loaded.")
        return user
    finally:
        connection.close()


def create_oauth_state(provider: str) -> str:
    raw_state = secrets.token_urlsafe(24)
    now = utc_now()
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO oauth_states (state_hash, provider, created_at, expires_at)
            VALUES (?, ?, ?, ?)
            """,
            (
                hash_token(raw_state),
                provider,
                now.isoformat(),
                (now + timedelta(minutes=10)).isoformat(),
            ),
        )
        connection.commit()
    finally:
        connection.close()
    return raw_state


def consume_oauth_state(provider: str, raw_state: str) -> bool:
    state_hash = hash_token(raw_state)
    connection = connect()
    try:
        row = connection.execute(
            """
            SELECT 1 FROM oauth_states
            WHERE state_hash = ? AND provider = ? AND expires_at >= ?
            """,
            (state_hash, provider, utc_now().isoformat()),
        ).fetchone()
        connection.execute("DELETE FROM oauth_states WHERE state_hash = ?", (state_hash,))
        connection.commit()
        return row is not None
    finally:
        connection.close()


def user_for_session(raw_token: str) -> UserAccount | None:
    connection = connect()
    try:
        row = connection.execute(
            """
            SELECT users.* FROM user_sessions
            JOIN users ON users.id = user_sessions.user_id
            WHERE user_sessions.token_hash = ? AND user_sessions.expires_at >= ?
            """,
            (hash_token(raw_token), utc_now().isoformat()),
        ).fetchone()
    finally:
        connection.close()
    return user_from_row(row) if row else None


def delete_session(raw_token: str) -> None:
    connection = connect()
    try:
        connection.execute("DELETE FROM user_sessions WHERE token_hash = ?", (hash_token(raw_token),))
        connection.commit()
    finally:
        connection.close()


def preferences_for_user(user_id: int | None) -> UserPreferences:
    if user_id is None:
        return clone_default_preferences()
    connection = connect()
    try:
        initialize_user_preferences(connection, user_id)
        settings_row = connection.execute("SELECT * FROM user_settings WHERE user_id = ?", (user_id,)).fetchone()
        ui_state_row = connection.execute("SELECT * FROM user_ui_state WHERE user_id = ?", (user_id,)).fetchone()
        follow_rows = connection.execute("SELECT * FROM user_follows WHERE user_id = ?", (user_id,)).fetchall()
        connection.commit()
    finally:
        connection.close()

    preferences = UserPreferences()
    if settings_row:
        preferences.f1_sessions = {F1Session(item) for item in json.loads(settings_row["f1_sessions"])}
        preferences.default_hide_spoilers = bool(settings_row["default_hide_spoilers"])
        preferences.timezone = settings_row["timezone"]
    if ui_state_row:
        try:
            preferences.ui_state = json.loads(ui_state_row["state_json"])
        except json.JSONDecodeError:
            preferences.ui_state = {}
    known_entities = list_entity_records()
    preferences.follows = {
        row["entity_id"]: Follow(
            entity_id=row["entity_id"],
            level=row["level"],
            notifications_enabled=bool(row["notifications_enabled"]),
            hide_spoilers=bool(row["hide_spoilers"]),
        )
        for row in follow_rows
        if row["entity_id"] in known_entities
    }
    return preferences


def set_user_follow(user_id: int, follow: Follow) -> None:
    if follow.entity_id not in list_entity_records():
        raise ValueError("Entity not found.")
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO user_follows (
                user_id, entity_id, level, notifications_enabled, hide_spoilers, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(user_id, entity_id) DO UPDATE SET
                level = excluded.level,
                notifications_enabled = excluded.notifications_enabled,
                hide_spoilers = excluded.hide_spoilers,
                updated_at = excluded.updated_at
            """,
            (
                user_id,
                follow.entity_id,
                follow_level_value(follow.level),
                int(follow.notifications_enabled),
                int(follow.hide_spoilers),
                utc_now().isoformat(),
            ),
        )
        connection.commit()
    finally:
        connection.close()


def set_user_f1_sessions(user_id: int, sessions: Iterable[F1Session]) -> None:
    connection = connect()
    try:
        initialize_user_preferences(connection, user_id)
        connection.execute(
            """
            UPDATE user_settings
            SET f1_sessions = ?, updated_at = ?
            WHERE user_id = ?
            """,
            (json.dumps([session.value for session in sessions]), utc_now().isoformat(), user_id),
        )
        connection.commit()
    finally:
        connection.close()


def set_user_hide_spoilers(user_id: int, hide_spoilers: bool) -> None:
    connection = connect()
    try:
        initialize_user_preferences(connection, user_id)
        connection.execute(
            """
            UPDATE user_settings
            SET default_hide_spoilers = ?, updated_at = ?
            WHERE user_id = ?
            """,
            (int(hide_spoilers), utc_now().isoformat(), user_id),
        )
        connection.commit()
    finally:
        connection.close()


def set_user_ui_state(user_id: int, state: dict) -> None:
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO user_ui_state (user_id, state_json, updated_at)
            VALUES (?, ?, ?)
            ON CONFLICT(user_id) DO UPDATE SET
                state_json = excluded.state_json,
                updated_at = excluded.updated_at
            """,
            (user_id, json.dumps(state), utc_now().isoformat()),
        )
        connection.commit()
    finally:
        connection.close()


def upsert_push_subscription(
    user_id: int,
    endpoint: str,
    p256dh: str,
    auth: str,
    user_agent: str | None = None,
) -> PushSubscription:
    subscription_id = "push_" + secrets.token_urlsafe(18)
    now = utc_now().isoformat()
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO push_subscriptions (
                id, user_id, endpoint, p256dh, auth, user_agent, enabled, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?)
            ON CONFLICT(endpoint) DO UPDATE SET
                user_id = excluded.user_id,
                p256dh = excluded.p256dh,
                auth = excluded.auth,
                user_agent = excluded.user_agent,
                enabled = 1,
                updated_at = excluded.updated_at
            """,
            (subscription_id, user_id, endpoint, p256dh, auth, user_agent, now, now),
        )
        connection.commit()
        row = connection.execute("SELECT * FROM push_subscriptions WHERE endpoint = ?", (endpoint,)).fetchone()
    finally:
        connection.close()
    if row is None:
        raise RuntimeError("Push subscription could not be stored.")
    return push_subscription_from_row(row)


def list_push_subscriptions(user_id: int | None = None, enabled_only: bool = True) -> list[PushSubscription]:
    clauses = []
    params: list[object] = []
    if user_id is not None:
        clauses.append("user_id = ?")
        params.append(user_id)
    if enabled_only:
        clauses.append("enabled = 1")
    sql = "SELECT * FROM push_subscriptions"
    if clauses:
        sql += " WHERE " + " AND ".join(clauses)
    sql += " ORDER BY updated_at DESC"
    connection = connect()
    try:
        rows = connection.execute(sql, params).fetchall()
    finally:
        connection.close()
    return [push_subscription_from_row(row) for row in rows]


def disable_push_subscription(endpoint: str) -> None:
    connection = connect()
    try:
        connection.execute(
            "UPDATE push_subscriptions SET enabled = 0, updated_at = ? WHERE endpoint = ?",
            (utc_now().isoformat(), endpoint),
        )
        connection.commit()
    finally:
        connection.close()


def list_notification_rules(user_id: int) -> list[NotificationRule]:
    connection = connect()
    try:
        rows = connection.execute(
            "SELECT * FROM notification_rules WHERE user_id = ? ORDER BY target_type, name",
            (user_id,),
        ).fetchall()
    finally:
        connection.close()
    return [notification_rule_from_row(row) for row in rows]


def upsert_notification_rule(
    user_id: int,
    name: str,
    target_type: str,
    target_id: str,
    minutes_before: int,
    enabled: bool = True,
    rule_id: str | None = None,
) -> NotificationRule:
    now = utc_now().isoformat()
    next_id = rule_id or "rule_" + secrets.token_urlsafe(18)
    minutes = max(0, min(int(minutes_before), 7 * 24 * 60))
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO notification_rules (
                id, user_id, name, enabled, target_type, target_id, minutes_before, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                enabled = excluded.enabled,
                target_type = excluded.target_type,
                target_id = excluded.target_id,
                minutes_before = excluded.minutes_before,
                updated_at = excluded.updated_at
            """,
            (next_id, user_id, name.strip() or "Reminder", int(enabled), target_type, target_id, minutes, now, now),
        )
        connection.commit()
        row = connection.execute("SELECT * FROM notification_rules WHERE id = ? AND user_id = ?", (next_id, user_id)).fetchone()
    finally:
        connection.close()
    if row is None:
        raise RuntimeError("Notification rule could not be stored.")
    return notification_rule_from_row(row)


def delete_notification_rule(user_id: int, rule_id: str) -> None:
    connection = connect()
    try:
        connection.execute("DELETE FROM notification_rules WHERE user_id = ? AND id = ?", (user_id, rule_id))
        connection.commit()
    finally:
        connection.close()


def list_all_notification_rules(enabled_only: bool = True) -> list[NotificationRule]:
    sql = "SELECT * FROM notification_rules"
    if enabled_only:
        sql += " WHERE enabled = 1"
    sql += " ORDER BY minutes_before DESC"
    connection = connect()
    try:
        rows = connection.execute(sql).fetchall()
    finally:
        connection.close()
    return [notification_rule_from_row(row) for row in rows]


def sent_notification_exists(user_id: int, event_id: str, rule_id: str, scheduled_for: datetime) -> bool:
    connection = connect()
    try:
        row = connection.execute(
            """
            SELECT 1 FROM sent_notifications
            WHERE user_id = ? AND event_id = ? AND rule_id = ? AND scheduled_for = ?
            """,
            (user_id, event_id, rule_id, scheduled_for.astimezone(timezone.utc).isoformat()),
        ).fetchone()
    finally:
        connection.close()
    return row is not None


def mark_notification_sent(user_id: int, event_id: str, rule_id: str, scheduled_for: datetime) -> None:
    connection = connect()
    try:
        connection.execute(
            """
            INSERT OR IGNORE INTO sent_notifications (user_id, event_id, rule_id, scheduled_for, sent_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                user_id,
                event_id,
                rule_id,
                scheduled_for.astimezone(timezone.utc).isoformat(),
                utc_now().isoformat(),
            ),
        )
        connection.commit()
    finally:
        connection.close()


def list_entity_records() -> dict[str, EntityRecord]:
    connection = connect()
    try:
        rows = connection.execute("SELECT * FROM entities ORDER BY sport, kind, name").fetchall()
        alias_rows = connection.execute("SELECT entity_id, alias FROM entity_aliases ORDER BY alias").fetchall()
        binding_rows = connection.execute(
            "SELECT entity_id, provider, binding_type, binding_value, metadata_json FROM entity_provider_bindings ORDER BY provider, binding_type"
        ).fetchall()
    finally:
        connection.close()

    aliases: dict[str, list[str]] = {}
    for row in alias_rows:
        aliases.setdefault(row["entity_id"], []).append(row["alias"])
    bindings: dict[str, list[EntityBinding]] = {}
    for row in binding_rows:
        bindings.setdefault(row["entity_id"], []).append(
            EntityBinding(
                provider=row["provider"],
                binding_type=row["binding_type"],
                value=row["binding_value"],
                metadata=json.loads(row["metadata_json"] or "{}"),
            )
        )
    return {
        row["id"]: EntityRecord(
            entity=Entity(row["id"], row["name"], Sport(row["sport"]), EntityKind(row["kind"]), row["color"]),
            aliases=aliases.get(row["id"], []),
            bindings=bindings.get(row["id"], []),
            is_seed=bool(row["is_seed"]),
            created_by_user_id=row["created_by_user_id"],
        )
        for row in rows
    }


def get_entity_record(entity_id: str) -> EntityRecord | None:
    return list_entity_records().get(entity_id)


def create_custom_entity(
    user_id: int,
    name: str,
    sport: Sport,
    kind: EntityKind,
    color: str,
    level: str,
    aliases: Iterable[str] = (),
    bindings: Iterable[EntityBinding] = (),
) -> EntityRecord:
    entity_id = slugify_entity_id(name)
    existing = list_entity_records()
    base_id = entity_id
    suffix = 2
    while entity_id in existing:
        entity_id = f"{base_id}_{suffix}"
        suffix += 1

    now = utc_now().isoformat()
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO entities (id, name, sport, kind, color, is_seed, created_by_user_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?)
            """,
            (entity_id, name.strip(), sport.value, kind.value, color, user_id, now, now),
        )
        upsert_entity_aliases(connection, entity_id, aliases)
        upsert_entity_bindings(connection, entity_id, bindings)
        connection.commit()
    finally:
        connection.close()
    set_user_follow(user_id, Follow(entity_id, level))
    record = get_entity_record(entity_id)
    if record is None:
        raise RuntimeError("Created entity could not be loaded.")
    return record


def update_custom_entity(
    user_id: int,
    entity_id: str,
    name: str,
    sport: Sport,
    kind: EntityKind,
    color: str,
    aliases: Iterable[str],
    bindings: Iterable[EntityBinding],
) -> EntityRecord:
    connection = connect()
    try:
        row = connection.execute("SELECT * FROM entities WHERE id = ?", (entity_id,)).fetchone()
        if not row:
            raise ValueError("Entity not found.")
        if bool(row["is_seed"]) or row["created_by_user_id"] != user_id:
            raise PermissionError("Only your custom entities can be edited.")
        connection.execute(
            """
            UPDATE entities
            SET name = ?, sport = ?, kind = ?, color = ?, updated_at = ?
            WHERE id = ?
            """,
            (name.strip(), sport.value, kind.value, color, utc_now().isoformat(), entity_id),
        )
        connection.execute("DELETE FROM entity_aliases WHERE entity_id = ?", (entity_id,))
        connection.execute("DELETE FROM entity_provider_bindings WHERE entity_id = ?", (entity_id,))
        upsert_entity_aliases(connection, entity_id, aliases)
        upsert_entity_bindings(connection, entity_id, bindings)
        connection.commit()
    finally:
        connection.close()
    record = get_entity_record(entity_id)
    if record is None:
        raise RuntimeError("Updated entity could not be loaded.")
    return record


def delete_or_hide_entity_for_user(user_id: int, entity_id: str) -> str:
    connection = connect()
    try:
        row = connection.execute("SELECT * FROM entities WHERE id = ?", (entity_id,)).fetchone()
        if not row:
            raise ValueError("Entity not found.")
        if bool(row["is_seed"]) or row["created_by_user_id"] != user_id:
            connection.execute(
                """
                INSERT INTO user_follows (
                    user_id, entity_id, level, notifications_enabled, hide_spoilers, updated_at
                )
                VALUES (?, ?, ?, 1, 1, ?)
                ON CONFLICT(user_id, entity_id) DO UPDATE SET
                    level = excluded.level,
                    updated_at = excluded.updated_at
                """,
                (user_id, entity_id, FollowLevel.HIDDEN.value, utc_now().isoformat()),
            )
            connection.commit()
            return "hidden"
        connection.execute("DELETE FROM user_follows WHERE entity_id = ?", (entity_id,))
        connection.execute("DELETE FROM entity_aliases WHERE entity_id = ?", (entity_id,))
        connection.execute("DELETE FROM entity_provider_bindings WHERE entity_id = ?", (entity_id,))
        connection.execute("DELETE FROM entities WHERE id = ?", (entity_id,))
        connection.commit()
        return "deleted"
    finally:
        connection.close()


def search_entity_records(query: str) -> list[EntityRecord]:
    text = normalize_search(query)
    if not text:
        return []
    records = list_entity_records().values()
    return [
        record
        for record in records
        if text in normalize_search(record.entity.name)
        or any(text in normalize_search(alias) for alias in record.aliases)
    ]


def provider_bindings_for(provider: str, binding_type: str | None = None) -> dict[str, list[str]]:
    output: dict[str, list[str]] = {}
    for entity_id, record in list_entity_records().items():
        for binding in record.bindings:
            if binding.provider != provider:
                continue
            if binding_type is not None and binding.binding_type != binding_type:
                continue
            output.setdefault(entity_id, []).append(binding.value)
    return output


def upsert_events(events: Iterable[Event]) -> None:
    items = list(events)
    if not items:
        return
    now = datetime.now(timezone.utc).isoformat()
    connection = connect()
    try:
        for event in items:
            payload = event_to_payload(event)
            connection.execute(
                """
                INSERT INTO events (
                    id, title, sport, starts_at, status, entity_ids, source,
                    competition, session_type, result_summary, importance,
                    raw_json, first_seen_at, last_seen_at, updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(id) DO UPDATE SET
                    title = excluded.title,
                    sport = excluded.sport,
                    starts_at = excluded.starts_at,
                    status = excluded.status,
                    entity_ids = excluded.entity_ids,
                    source = excluded.source,
                    competition = excluded.competition,
                    session_type = excluded.session_type,
                    result_summary = excluded.result_summary,
                    importance = excluded.importance,
                    raw_json = excluded.raw_json,
                    last_seen_at = excluded.last_seen_at,
                    updated_at = excluded.updated_at
                """,
                (
                    event.id,
                    event.title,
                    event.sport.value,
                    event.starts_at.isoformat() if event.starts_at else None,
                    event.status.value,
                    json.dumps(event.entity_ids, ensure_ascii=False),
                    event.source,
                    event.competition,
                    event.session_type.value if event.session_type else None,
                    event.result_summary,
                    event.importance,
                    json.dumps(payload, ensure_ascii=False),
                    now,
                    now,
                    now,
                ),
            )
        connection.commit()
    finally:
        connection.close()


def delete_stale_events_for_source(
    source: str,
    start: datetime | None,
    end: datetime | None,
    keep_ids: Iterable[str],
) -> None:
    """Remove provider events that disappeared from a successful refresh.

    Provider payloads can change shape over time. Without cleanup, old aggregate
    IDs stay in the database next to newer split events, which is especially
    visible for calendar-like providers such as F4 weekends.
    """

    ids = list(dict.fromkeys(keep_ids))
    if not ids:
        return

    clauses = ["source = ?"]
    params: list[str] = [source]
    if start is not None:
        clauses.append("(starts_at IS NULL OR starts_at >= ?)")
        params.append(start.astimezone(timezone.utc).isoformat())
    if end is not None:
        clauses.append("(starts_at IS NULL OR starts_at < ?)")
        params.append(end.astimezone(timezone.utc).isoformat())

    placeholders = ", ".join("?" for _ in ids)
    clauses.append(f"id NOT IN ({placeholders})")
    params.extend(ids)

    connection = connect()
    try:
        connection.execute(f"DELETE FROM events WHERE {' AND '.join(clauses)}", tuple(params))
        connection.commit()
    finally:
        connection.close()


def list_events(start: datetime | None = None, end: datetime | None = None) -> list[Event]:
    clauses = []
    params: list[str] = []
    if start is not None:
        clauses.append("(starts_at IS NULL OR starts_at >= ?)")
        params.append(start.astimezone(timezone.utc).isoformat())
    if end is not None:
        clauses.append("(starts_at IS NULL OR starts_at < ?)")
        params.append(end.astimezone(timezone.utc).isoformat())

    sql = "SELECT raw_json FROM events"
    if clauses:
        sql += " WHERE " + " AND ".join(clauses)
    sql += " ORDER BY starts_at IS NULL, starts_at, importance DESC"

    connection = connect()
    try:
        rows = connection.execute(sql, params).fetchall()
    finally:
        connection.close()
    return [event_from_payload(json.loads(row["raw_json"])) for row in rows]


def get_event(event_id: str) -> Event | None:
    connection = connect()
    try:
        row = connection.execute("SELECT raw_json FROM events WHERE id = ?", (event_id,)).fetchone()
    finally:
        connection.close()
    if not row:
        return None
    return event_from_payload(json.loads(row["raw_json"]))


def mark_provider_fetch(provider_name: str, cache_key: str, status: str, error: str | None = None) -> None:
    now = datetime.now(timezone.utc).isoformat()
    connection = connect()
    try:
        connection.execute(
            """
            INSERT INTO provider_fetches (provider_name, cache_key, fetched_at, status, error)
            VALUES (?, ?, ?, ?, ?)
            ON CONFLICT(provider_name, cache_key) DO UPDATE SET
                fetched_at = excluded.fetched_at,
                status = excluded.status,
                error = excluded.error
            """,
            (provider_name, cache_key, now, status, error),
        )
        connection.commit()
    finally:
        connection.close()


def provider_fetched_at(provider_name: str, cache_key: str) -> datetime | None:
    state = provider_fetch_state(provider_name, cache_key)
    return state.fetched_at if state else None


def provider_fetch_state(provider_name: str, cache_key: str) -> ProviderFetchState | None:
    connection = connect()
    try:
        row = connection.execute(
            "SELECT fetched_at, status, error FROM provider_fetches WHERE provider_name = ? AND cache_key = ?",
            (provider_name, cache_key),
        ).fetchone()
    finally:
        connection.close()
    if not row:
        return None
    try:
        fetched_at = datetime.fromisoformat(row["fetched_at"]).astimezone(timezone.utc)
    except ValueError:
        return None
    return ProviderFetchState(fetched_at=fetched_at, status=row["status"], error=row["error"])


def event_to_payload(event: Event) -> dict:
    payload = asdict(event)
    payload["sport"] = event.sport.value
    payload["status"] = event.status.value
    payload["session_type"] = event.session_type.value if event.session_type else None
    payload["starts_at"] = event.starts_at.isoformat() if event.starts_at else None
    return payload


def event_from_payload(payload: dict) -> Event:
    starts_at = payload.get("starts_at")
    return Event(
        id=payload["id"],
        title=payload["title"],
        sport=Sport(payload["sport"]),
        starts_at=datetime.fromisoformat(starts_at).astimezone(timezone.utc) if starts_at else None,
        status=EventStatus(payload["status"]),
        entity_ids=list(payload.get("entity_ids", [])),
        source=payload["source"],
        competition=payload.get("competition"),
        session_type=F1Session(payload["session_type"]) if payload.get("session_type") else None,
        result_summary=payload.get("result_summary"),
        importance=int(payload.get("importance", 50)),
    )


def initialize_user_preferences(connection: sqlite3.Connection, user_id: int) -> None:
    now = utc_now().isoformat()
    settings_exists = connection.execute("SELECT 1 FROM user_settings WHERE user_id = ?", (user_id,)).fetchone()
    if not settings_exists:
        default_sessions = [session.value for session in DEFAULT_PREFERENCES.f1_sessions]
        connection.execute(
            """
            INSERT INTO user_settings (user_id, f1_sessions, default_hide_spoilers, timezone, updated_at)
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                user_id,
                json.dumps(default_sessions),
                int(DEFAULT_PREFERENCES.default_hide_spoilers),
                DEFAULT_PREFERENCES.timezone,
                now,
            ),
        )
    for follow in DEFAULT_PREFERENCES.follows.values():
        connection.execute(
            """
            INSERT OR IGNORE INTO user_follows (
                user_id, entity_id, level, notifications_enabled, hide_spoilers, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                user_id,
                follow.entity_id,
                follow_level_value(follow.level),
                int(follow.notifications_enabled),
                int(follow.hide_spoilers),
                now,
            ),
        )


def sync_seed_entities(connection: sqlite3.Connection) -> None:
    now = utc_now().isoformat()
    for entity in ENTITIES.values():
        connection.execute(
            """
            INSERT INTO entities (id, name, sport, kind, color, is_seed, created_by_user_id, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, 1, NULL, ?, ?)
            ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                sport = excluded.sport,
                kind = excluded.kind,
                color = excluded.color,
                is_seed = 1,
                updated_at = excluded.updated_at
            """,
            (entity.id, entity.name, entity.sport.value, entity.kind.value, entity.color, now, now),
        )
        upsert_entity_aliases(connection, entity.id, default_aliases_for_entity(entity))
        upsert_entity_bindings(connection, entity.id, default_bindings_for_entity(entity.id))


def upsert_entity_aliases(connection: sqlite3.Connection, entity_id: str, aliases: Iterable[str]) -> None:
    for alias in {alias.strip() for alias in aliases if alias.strip()}:
        connection.execute(
            "INSERT OR IGNORE INTO entity_aliases (entity_id, alias) VALUES (?, ?)",
            (entity_id, alias),
        )


def upsert_entity_bindings(connection: sqlite3.Connection, entity_id: str, bindings: Iterable[EntityBinding]) -> None:
    for binding in bindings:
        connection.execute(
            """
            INSERT OR IGNORE INTO entity_provider_bindings (
                entity_id, provider, binding_type, binding_value, metadata_json
            )
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                entity_id,
                binding.provider,
                binding.binding_type,
                binding.value,
                json.dumps(binding.metadata, ensure_ascii=False),
            ),
        )


def default_aliases_for_entity(entity: Entity) -> list[str]:
    aliases = [entity.name]
    if entity.name.endswith(" NT"):
        aliases.append(entity.name.removesuffix(" NT"))
    if entity.name.startswith("FC "):
        aliases.append(entity.name.removeprefix("FC "))
    if entity.id == "navi_cs2":
        aliases.extend(["NAVI", "Natus Vincere"])
    return aliases


def default_bindings_for_entity(entity_id: str) -> list[EntityBinding]:
    values: dict[str, list[tuple[str, str]]] = {
        "barcelona": [("espn", "team_id", "83"), ("espn", "league_slug", "esp.1"), ("espn", "league_slug", "uefa.champions")],
        "ukraine_nt": [("espn", "team_id", "457"), ("espn", "league_slug", "uefa.nations"), ("espn", "league_slug", "fifa.world"), ("espn", "league_slug", "uefa.euro")],
        "ucl": [("espn", "league_slug", "uefa.champions"), ("football-data", "competition_code", "CL")],
        "world_cup": [("espn", "league_slug", "fifa.world"), ("football-data", "competition_code", "WC")],
        "euro": [("espn", "league_slug", "uefa.euro"), ("football-data", "competition_code", "EC")],
        "navi_cs2": [("pandascore", "team_query", "Natus Vincere"), ("hltv", "team_query", "Natus Vincere")],
    }
    return [EntityBinding(provider, binding_type, value) for provider, binding_type, value in values.get(entity_id, [])]


def slugify_entity_id(value: str) -> str:
    output = []
    for char in value.lower().strip():
        if char.isalnum():
            output.append(char)
        elif output and output[-1] != "_":
            output.append("_")
    slug = "".join(output).strip("_")
    return slug or f"entity_{secrets.token_hex(4)}"


def normalize_search(value: str) -> str:
    return " ".join(value.lower().strip().split())


def get_user_by_id_with_connection(connection: sqlite3.Connection, user_id: int) -> UserAccount | None:
    row = connection.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()
    return user_from_row(row) if row else None


def user_from_row(row: sqlite3.Row) -> UserAccount:
    verified_at = row["email_verified_at"]
    return UserAccount(
        id=int(row["id"]),
        email=row["email"],
        email_verified_at=datetime.fromisoformat(verified_at).astimezone(timezone.utc) if verified_at else None,
        created_at=datetime.fromisoformat(row["created_at"]).astimezone(timezone.utc),
    )


def push_subscription_from_row(row) -> PushSubscription:
    return PushSubscription(
        id=row["id"],
        user_id=int(row["user_id"]),
        endpoint=row["endpoint"],
        p256dh=row["p256dh"],
        auth=row["auth"],
        user_agent=row["user_agent"],
        enabled=bool(row["enabled"]),
        created_at=datetime.fromisoformat(row["created_at"]).astimezone(timezone.utc),
        updated_at=datetime.fromisoformat(row["updated_at"]).astimezone(timezone.utc),
    )


def notification_rule_from_row(row) -> NotificationRule:
    return NotificationRule(
        id=row["id"],
        user_id=int(row["user_id"]),
        name=row["name"],
        enabled=bool(row["enabled"]),
        target_type=row["target_type"],
        target_id=row["target_id"],
        minutes_before=int(row["minutes_before"]),
        created_at=datetime.fromisoformat(row["created_at"]).astimezone(timezone.utc),
        updated_at=datetime.fromisoformat(row["updated_at"]).astimezone(timezone.utc),
    )


def clone_default_preferences() -> UserPreferences:
    return UserPreferences(
        follows={
            entity_id: Follow(
                entity_id=follow.entity_id,
                level=follow.level,
                notifications_enabled=follow.notifications_enabled,
                hide_spoilers=follow.hide_spoilers,
            )
            for entity_id, follow in DEFAULT_PREFERENCES.follows.items()
        },
        f1_sessions=set(DEFAULT_PREFERENCES.f1_sessions),
        default_hide_spoilers=DEFAULT_PREFERENCES.default_hide_spoilers,
        timezone=DEFAULT_PREFERENCES.timezone,
    )


def normalize_email(email: str) -> str:
    return email.strip().lower()


def hash_password(password: str) -> str:
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, PASSWORD_ITERATIONS)
    return "pbkdf2_sha256${}${}${}".format(
        PASSWORD_ITERATIONS,
        base64.urlsafe_b64encode(salt).decode("ascii"),
        base64.urlsafe_b64encode(digest).decode("ascii"),
    )


def verify_password(password: str, stored: str) -> bool:
    try:
        algorithm, iterations, salt_b64, digest_b64 = stored.split("$", 3)
    except ValueError:
        return False
    if algorithm != "pbkdf2_sha256":
        return False
    salt = base64.urlsafe_b64decode(salt_b64.encode("ascii"))
    expected = base64.urlsafe_b64decode(digest_b64.encode("ascii"))
    actual = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, int(iterations))
    return hmac.compare_digest(actual, expected)


def hash_token(raw_token: str) -> str:
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def follow_level_value(value) -> str:
    return value.value if hasattr(value, "value") else str(value)
